name: Embed code in README

on:
  pull_request:
    branches:
      - master

jobs:
  embed_code:
    name: Embed Code
    runs-on: windows-latest
    
    strategy:
      matrix:
        dotnet-version: ['6.0.x']
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
        
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build .\BuildPicoC\BuildPicoC.csproj --configuration Release --no-restore
        
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Build Update Hour Prices release
        run: msbuild .\UpdateHourPrices\UpdateHourPrices.vcxproj -t:rebuild -verbosity:diag -property:Configuration=Release

      - name: Build Test Hour Prices release
        run: msbuild .\Tests\UpdateHourPrices.Tests\UpdateHourPrices.Tests.vcxproj -t:rebuild -verbosity:diag -property:Configuration=Release

      - name: Setup VSTest and add to PATH
        uses: darenm/Setup-VSTest@v1
        id: setup_vstest

      - name: Run VSTest
        id: run_vstest
        run: vstest.console.exe .\Tests\UpdateHourPrices.Tests\Release\UpdateHourPrices.Tests.obj

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: 14
          
      - name: Install dependencies
        run: npm install -g embedme
        
      - name: Update README
        run: embedme README.md
      
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Updated README'
          add: 'README.md'
